Milestone Completion
tomdan-ai/Capstone-Project pull request #1
Opened 2023-03-16 22:42 UTC by tomdan-ai

### **Capstone Project**

- [ ] Add Hompage for Mobile
- [ ] Add Homepage for Desktop
- [ ] Add about page Mobile
- [ ] Add about page for Desktop
- [ ] Add JS for dynamics/Menu
- [ ] Add styles and responsiveness
- [ ] Add images
- [ ] Add Linters/Follow gitflows

2023-03-16 23:22 UTC, vickymarz requested changes
Hi @tomdan-ai, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️

- [ ] I think you should make another video presentation because the one you did, you didn't showcase your website and its features. Please redo the video presentation

_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-16 23:22 UTC, vickymarz commented on index.html
> +            /></a>
- [ ] Good job so far 👍🏽 . Your logo is currently not displaying. KIndly fix the relative path of the image so that it will be visible to the DOM

![image](https://user-images.githubusercontent.com/63473584/225771084-5fec386d-50d0-4f3b-a8c7-9a1751dbdb71.png)

2023-03-16 23:22 UTC, vickymarz commented on index.html
> +                </h1>
- [x] KIndly increase the font size of your introductory text to match the design guideline. Making it bolder will make it easily readable which is a good user experience 👍🏽 

Design guideline
![image](https://user-images.githubusercontent.com/63473584/225772322-7a8f80cf-7a0f-415b-ab47-5fc46088d784.png)

Your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/225772384-9be7e7fb-3cdb-4425-b8c0-f1fd85071685.png)

2023-03-16 23:22 UTC, vickymarz commented on index.html
> +                >
- [ ]  Please see that this event date is currently not visible which will make it difficult for people with eye impairment to read the texts which is not a good user experience. I will advise you to either change the background image on the hero section or change the font color of the text. 👍🏽

your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/225772746-c91bc911-4a11-43be-90ac-e830c1f47db0.png)

design guidelines 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/225772817-d479ab72-db79-42eb-8e76-44879963ceb4.png)

2023-03-16 23:22 UTC, vickymarz commented on index.html
> +                    />
- [ ] Your images size are breaking or splitting. Kindly use percentages on the image size instead of pixels so that the image can scale depending on the screen size

![image](https://user-images.githubusercontent.com/63473584/225773178-e1ef5746-94b9-49a1-b368-3002b5b77962.png)

2023-03-17 10:14 UTC, OyePriscilla requested changes
Hi @tomdan-ai 👏 👏, 

Great work on making the changes requested by a previous reviewer 👏 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Use JavaScript event listener 👍 
Use JS object to store data ✔️ 
DOM manipulation ✔️ 

 ## Required Changes ♻️

- [ ] Please in the video presentation, kindly **show a piece of code** that you find interesting or proud of in the process of building the App according to the requirement.  ℹ️ 

## Optional suggestions

- [optional] I will implore you to carefully look through this [README file template](https://github.com/microverseinc/readme-template) and format yours neatly as well. Please make sure that `tech stack` and other headers in the `Getting Started` section are added.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-17 10:14 UTC, OyePriscilla commented on index.html
> +      <div class="container">
- [optional] I noticed that you did not align your footer logo to the left according to the given design, and more so, the background-color is different. It always great that we carefully pay attention to details as developers. 👍

2023-03-17 10:14 UTC, OyePriscilla commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [optional] Please kindly fix this broken link, I notice you have `LICENSE` file in your root folder not `MIT.md` as we have it here. 👍 This will make your repo to be more informative. ℹ️

2023-03-17 14:10 UTC, hiromataba approved these changes
# Status: Approved :tada: :tada: :tada: 
Hi @tomdan-ai     :wave: :wave: 

![200w](https://user-images.githubusercontent.com/75126481/151663786-7e0aa330-6769-4ab2-a051-3754be515be9.gif)  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-17 14:18 UTC, merged